### ISSUE TITLE
[Feature request] Description of parameters of ATTACKs in ScriptView

### ISSUE THREAD

**Issue by shwaka** [rubendal/ssbu#17]
I think some of the readers don't know the meaning of the parameters. So it would be nice if descriptions are shown as in the following picture.

![description](https://user-images.githubusercontent.com/18346326/100581024-530dfa00-332a-11eb-80e8-ce33433eac0c.png)

How do you feel about this feature?
I have implemented a prototype for this feature, which can be tested from [shwaka/ssbu at description](https://github.com/shwaka/ssbu/tree/description).

If you like this feature, I'm willing to make a PR. But there is a problem. Since I don't know the parameters well, I can't write the descriptions. Some of them are found at [Glossary](https://rubendal.github.io/ssbu/#/Glossary), but the others are not. Is there some reference for these?

**Comment by rubendal** [comment]
A nice feature to have for scripts since a lot of people don't understand some parameters like FacingRestrict or Hitbits since there's few or none documentation about these

For the parameter descriptions that you feel you don't know to make them I could write them after merging the PR and before deploying the feature to the site

**Comment by shwaka** [comment]
Thank you for the suggestion!
I will make a PR as soon as possible.

**Comment by rubendal** [comment]
Feature is live on site
